const moviesDB = {
  page: 1,
  total_results: 86,
  total_pages: 5,
  results: [
    {
      vote_count: 7768,
      id: 246655,
      video: false,
      vote_average: 6.5,
      title: 'X-Men: Apocalypse',
      popularity: 26.146,
      poster_path: '/zSouWWrySXshPCT4t3UKCQGayyo.jpg',
      original_language: 'en',
      original_title: 'X-Men: Apocalypse',
      genre_ids: [
        28,
        12,
        878,
        14,
      ],
      backdrop_path: '/oQWWth5AOtbWG9o8SCAviGcADed.jpg',
      adult: false,
      overview: "After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.",
      release_date: '2016-05-18',
    },
    {
      vote_count: 9476,
      id: 127585,
      video: false,
      vote_average: 7.5,
      title: 'X-Men: Days of Future Past',
      popularity: 26.118,
      poster_path: '/pb1IURTkK5rImP9ZV83lxJO2us7.jpg',
      original_language: 'en',
      original_title: 'X-Men: Days of Future Past',
      genre_ids: [
        28,
        12,
        14,
        878,
      ],
      backdrop_path: '/5LBcSLHAtEIIgvNkA2dPmYH5wR7.jpg',
      adult: false,
      overview: 'The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.',
      release_date: '2014-05-15',
    },
    {
      vote_count: 0,
      id: 320288,
      video: false,
      vote_average: 0,
      title: 'Dark Phoenix',
      popularity: 15.949,
      poster_path: '/b8PZgPqbsIJrz9FlPKHvYQWmGMt.jpg',
      original_language: 'en',
      original_title: 'Dark Phoenix',
      genre_ids: [
        28,
        878,
      ],
      backdrop_path: '/6H0CfLRcgq0Pcq34wNypC2V3W41.jpg',
      adult: false,
      overview: "During a rescue mission in space, Jean is nearly killed when she is hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. Wrestling with this entity inside her, Jean unleashes her powers in ways she can neither comprehend nor contain. With Jean spiraling our of control, and hurting the ones she loves most, she begins to unravel the very fabric that holds the X-Men together. Now, with this family falling apart, they must find a way to unite - not only to save Jean's soul, but to save our very planet from aliens who wish to weaponize this force and rule the galaxy.",
      release_date: '2019-06-05',
    },
    {
      vote_count: 68,
      id: 447152,
      video: true,
      vote_average: 6.8,
      title: 'Wolverine Unleashed: The Complete Origins',
      popularity: 5.389,
      poster_path: '/kz77FuYQkUzqX1tPQALHNsJzdrj.jpg',
      original_language: 'en',
      original_title: 'Wolverine Unleashed: The Complete Origins',
      genre_ids: [
        28,
      ],
      backdrop_path: '/q3wHQkt6U0kslFMrDTdNJDhWQBp.jpg',
      adult: false,
      overview: "Producer Lauren Schuler Donner starts this behind-the-scenes piece off by discussing how they initially wanted to tell Wolverine's Japan arc, but how the studio insisted that they give audiences an origins story first. What follows is a short, Hugh Jackman-centric look at the film's production, focusing on the character of Wolverine. The film's stunt coordinator discusses Jackman's commitment to bulking up-drinking a dozen egg whites a day and going on an intense fitness regime-and director Gavin Hood explains Wolverine's degree of self-loathing about his own nature. We also see some of the design work that went into the film, including the sculpting of young Logan's bone claws and the re-invention of the adamantium tank. Jackman comes off personable as always, and it's clear that he really loves this role.",
      release_date: '2009-09-15',
    },
    {
      vote_count: 56,
      id: 447161,
      video: true,
      vote_average: 7,
      title: 'X-Men: Reunited',
      popularity: 3.166,
      poster_path: null,
      original_language: 'en',
      original_title: 'X-Men: Reunited',
      genre_ids: [
        99,
      ],
      backdrop_path: null,
      adult: false,
      overview: 'This making-of piece looks at the genesis of this project and how Singer wanted to reunite the original cast again.',
      release_date: '2014-11-14',
    },
    {
      vote_count: 19,
      id: 37713,
      video: false,
      vote_average: 6.5,
      title: 'X-Men: Pryde of the X-Men',
      popularity: 2.103,
      poster_path: '/208meMFoKbMGyho4HJ85h7wRdmD.jpg',
      original_language: 'en',
      original_title: 'X-Men: Pryde of the X-Men',
      genre_ids: [
        16,
        28,
      ],
      backdrop_path: '/qaxuPRmM8MnYBDCWbZXxQ80RpVv.jpg',
      adult: false,
      overview: 'Pryde of the X-Men was a short-lived series about the X-Men, with the main character being Kitty Pryde (whose alias is Shadow Cat, though she never becomes Shadow Cat in the series), which is why the series is titled Pryde of the X-Men. The show was produced by Marvel Productions and Sunbow Productions, who made a pilot for NBC. The pilot aired, but for unknown reasons, it was never turned into a full-blown series. Despite it not becoming a full series, the pilot has aired in syndication, and was later released on video.',
      release_date: '1989-07-01',
    },
    {
      vote_count: 6403,
      id: 36657,
      video: false,
      vote_average: 6.9,
      title: 'X-Men',
      popularity: 1.112,
      poster_path: '/4kYj7fUJzhEg7xz8J3oMPi7gDww.jpg',
      original_language: 'en',
      original_title: 'X-Men',
      genre_ids: [
        12,
        28,
        878,
      ],
      backdrop_path: '/xm75A18CE7Wc6J9k2ZidFyqJ6rX.jpg',
      adult: false,
      overview: 'Two mutants, Rogue and Wolverine, come to a private academy for their kind whose resident superhero team, the X-Men, must oppose a terrorist organization with similar powers.',
      release_date: '2000-07-13',
    },
    {
      vote_count: 32,
      id: 447399,
      video: true,
      vote_average: 6.1,
      title: 'X-Men: The Mutant Watch',
      popularity: 2.626,
      poster_path: '/2BSZiURkEKgpNLIPjIRUEw3pASh.jpg',
      original_language: 'en',
      original_title: 'X-Men: The Mutant Watch',
      genre_ids: [
        99,
      ],
      backdrop_path: '/jDWJoj7YjZPjaRcq676OIJ7hdwC.jpg',
      adult: false,
      overview: 'While Senator Kelly addresses a senate committee about the supposed mutant menace, we learn about the making of the movie, X-Men.',
      release_date: '2000-07-02',
    },
    {
      vote_count: 0,
      id: 340102,
      video: false,
      vote_average: 0,
      title: 'The New Mutants',
      popularity: 8.396,
      poster_path: '/5AI4Y7KUTG2WDyuBsqeClLTind5.jpg',
      original_language: 'en',
      original_title: 'The New Mutants',
      genre_ids: [
        28,
        12,
        27,
        878,
      ],
      backdrop_path: '/nmzIYvr64K66ddpCdVdh1bzBwyF.jpg',
      adult: false,
      overview: "The story of the New Mutants, a team of mutant heroes comprised of the first graduates from Charles Xavier's school.",
      release_date: '2019-08-01',
    },
    {
      vote_count: 6100,
      id: 2080,
      video: false,
      vote_average: 6.2,
      title: 'X-Men Origins: Wolverine',
      popularity: 1.603,
      poster_path: '/kqO36IYvWbRKMPiUeiVZUFH06Rc.jpg',
      original_language: 'en',
      original_title: 'X-Men Origins: Wolverine',
      genre_ids: [
        12,
        28,
        53,
        878,
      ],
      backdrop_path: '/mEuDxpLNBCarVgXRqDznHT7bdS8.jpg',
      adult: false,
      overview: 'After seeking to live a normal life, Logan sets out to avenge the death of his girlfriend by undergoing the mutant Weapon X program and becoming Wolverine.',
      release_date: '2009-04-28',
    },
    {
      vote_count: 11,
      id: 447167,
      video: true,
      vote_average: 5.4,
      title: 'X-Men: Apocalypse Unearthed',
      popularity: 1.418,
      poster_path: null,
      original_language: 'en',
      original_title: 'X-Men: Apocalypse Unearthed',
      genre_ids: [
        99,
      ],
      backdrop_path: null,
      adult: false,
      overview: 'A six-part documentary. We get info about examines story/character areas and connections to other movies, cast and performances, costumes, makeup and effects, stunts/action, production design and photography, and general thoughts.',
      release_date: '2016-11-04',
    },
    {
      vote_count: 5717,
      id: 36658,
      video: false,
      vote_average: 6.9,
      title: 'X2',
      popularity: 0.998,
      poster_path: '/2ucMY4dPE4gGLPgDdYgyggYHBkF.jpg',
      original_language: 'en',
      original_title: 'X2',
      genre_ids: [
        12,
        28,
        878,
        53,
      ],
      backdrop_path: '/u2FxA8fDt0uQAnHKTwWGgkPShoL.jpg',
      adult: false,
      overview: "Professor Charles Xavier and his team of genetically gifted superheroes face a rising tide of anti-mutant sentiment led by Col. William Stryker. Storm, Wolverine and Jean Grey must join their usual nemeses –  Magneto and Mystique – to unhinge Stryker's scheme to exterminate all mutants.",
      release_date: '2003-04-24',
    },
    {
      vote_count: 11,
      id: 81946,
      video: false,
      vote_average: 6.4,
      title: 'X-Men: Production Scrapbook',
      popularity: 1.56,
      poster_path: '/iN9DjcdY90ytdn63MHawSRv1fTl.jpg',
      original_language: 'en',
      original_title: 'X-Men: Production Scrapbook',
      genre_ids: [
        99,
      ],
      backdrop_path: '/bk3mL984lTBwsjS5FJ1pkRPMW0w.jpg',
      adult: false,
      overview: '',
      release_date: '2000-11-02',
    },
    {
      vote_count: 0,
      id: 560583,
      video: false,
      vote_average: 0,
      title: 'X-Men',
      popularity: 0.6,
      poster_path: '/6YwJLGT1Dgcv86c1Wg1r7kx4jSv.jpg',
      original_language: 'en',
      original_title: 'X-Men',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview: '',
      release_date: '1993-09-25',
    },
    {
      vote_count: 9,
      id: 447162,
      video: true,
      vote_average: 6.2,
      title: 'X-Men: Unguarded',
      popularity: 0.992,
      poster_path: null,
      original_language: 'en',
      original_title: 'X-Men: Unguarded',
      genre_ids: [
        99,
      ],
      backdrop_path: null,
      adult: false,
      overview: "The film's all-star ensemble cast joins director Bryan Singer and screenwriter Simon Kinberg to share their favorite stories from the set.",
      release_date: '2015-07-14',
    },
    {
      vote_count: 5495,
      id: 36668,
      video: false,
      vote_average: 6.4,
      title: 'X-Men: The Last Stand',
      popularity: 1.01,
      poster_path: '/9jsW4RurucTwCEtA5iWV2PmIv11.jpg',
      original_language: 'en',
      original_title: 'X-Men: The Last Stand',
      genre_ids: [
        12,
        28,
        878,
        53,
      ],
      backdrop_path: '/w3Yc8wi2jYLaOyCW6b6svf1B0MG.jpg',
      adult: false,
      overview: "When a cure is found to treat mutations, lines are drawn amongst the X-Men and The Brotherhood, a band of powerful mutants organized under Xavier's former ally, Magneto.",
      release_date: '2006-05-24',
    },
    {
      vote_count: 7748,
      id: 49538,
      video: false,
      vote_average: 7.2,
      title: 'X-Men: First Class',
      popularity: 0.94,
      poster_path: '/7SSm7BfzFoVzmd6fCDccj7qRxc8.jpg',
      original_language: 'en',
      original_title: 'X-Men: First Class',
      genre_ids: [
        28,
        878,
        12,
      ],
      backdrop_path: '/39nstYsfjR6ggyKTtB4Joga2fs8.jpg',
      adult: false,
      overview: 'Before Charles Xavier and Erik Lensherr took the names Professor X and Magneto, they were two young men discovering their powers for the first time. Before they were arch-enemies, they were closest of friends, working together with other mutants (some familiar, some new), to stop the greatest threat the world has ever known.',
      release_date: '2011-06-01',
    },
    {
      vote_count: 6,
      id: 447141,
      video: true,
      vote_average: 6.3,
      title: 'X-Men: Evolution of a Trilogy',
      popularity: 1.335,
      poster_path: null,
      original_language: 'en',
      original_title: 'X-Men: Evolution of a Trilogy',
      genre_ids: [
        99,
      ],
      backdrop_path: null,
      adult: false,
      overview: 'A behind the scenes look at the making of the X-Men trilogy made up out of interviews shot during the production of all three films.',
      release_date: '2006-10-02',
    },
    {
      vote_count: 4,
      id: 447143,
      video: true,
      vote_average: 6,
      title: 'X-Men: The Excitement Continues',
      popularity: 0.84,
      poster_path: '/9o33R2EUkgBOIfODaarcfRO2VM1.jpg',
      original_language: 'en',
      original_title: 'X-Men: The Excitement Continues',
      genre_ids: [
        99,
      ],
      backdrop_path: null,
      adult: false,
      overview: 'A behind the scenes look at the making of X-men: The Last Stand.',
      release_date: '2006-10-02',
    },
    {
      vote_count: 4,
      id: 447127,
      video: true,
      vote_average: 5.3,
      title: 'The Secret Origin of X-Men',
      popularity: 1.021,
      poster_path: null,
      original_language: 'en',
      original_title: 'The Secret Origin of X-Men',
      genre_ids: [
        99,
      ],
      backdrop_path: null,
      adult: false,
      overview: 'This title, about the creation of the comic book X-Men, is featured on the DVD for X2.',
      release_date: '2003-11-25',
    },
  ],
};

module.exports = moviesDB;
