const hulu = [
  'Fairy Tail',
  'Dragon Ball',
  'Naruto Shippūden',
  'Gotham',
  'Family Guy',
  "Grey's Anatomy",
  'The Simpsons',
  'The Gifted',
  'Brooklyn Nine-Nine',
  'Law & Order: Special Victims Unit',
  'Vikings',
  'Tokyo Ghoul',
  'Modern Family',
  'South Park',
  'American Dad!',
  'One Piece',
  'Prison Break',
  'The Orville',
  'Sword Art Online',
  'Bleach',
  'The Good Doctor',
  "Marvel's Agents of S.H.I.E.L.D.",
  'Lethal Weapon',
  'Rick and Morty',
  'Hunter x Hunter',
  'Food Wars!: Shokugeki no Soma',
  'My Hero Academia',
  'Sesame Street',
  'Black Clover',
  'Chicago Fire',
  'Naruto',
  'Date a Live',
  'High School DxD',
  'Siren',
  'Fear the Walking Dead',
  'How to Get Away with Murder',
  'The Promised Neverland',
  'Pokémon',
  'Dexter',
  'Chicago P.D.',
  'One-Punch Man',
  'Blindspot',
  'Pretty Little Liars',
  'Elementary',
  'Death Note',
  'Futurama',
  'Fullmetal Alchemist: Brotherhood',
  'American Horror Story',
  'Shadowhunters',
  'Overlord',
  'Smallville',
  'How I Met Your Mother',
  'Case Closed',
  'The Passage',
  'Dark Shadows',
  'Survivor',
  'Twin Peaks',
  'Homeland',
  'Future Man',
  '9-1-1',
  'Blue Bloods',
  'CSI: Crime Scene Investigation',
  'The Resident',
  'Ray Donovan',
  'Empire',
  'Coronation Street',
  'Bones',
  'The Future Diary',
  'New Amsterdam',
  'Manifest',
  'The Middle',
  'Scrubs',
  'The Tonight Show Starring Jimmy Fallon',
  'Stargate SG-1',
  'This Is Us',
  'Code Geass: Lelouch of the Rebellion',
  'Chicago Med',
  'Chivalry of a Failed Knight',
  'CSI: Miami',
  'Mom',
  'New Girl',
  'Adventure Time',
  'Legion',
  'Noragami',
  'Last Man Standing',
  'Lost',
  'Sons of Anarchy',
  'Parasyte -the maxim-',
  'Attack on Titan',
  'Full House',
  'Archer',
  'Steins;Gate',
  'Blue Exorcist',
  'Assassination Classroom',
  "It's Always Sunny in Philadelphia",
  'Elfen Lied',
  'Seinfeld',
  'Mayday',
  'Knight Rider',
  'Desperate Housewives',
  'The Good Wife',
  'Star Trek',
  "Bob's Burgers",
  'Timeless',
  'How Not to Summon a Demon Lord',
  'Will & Grace',
  'Community',
  'Gravity Falls',
  'The X-Files',
  'American Idol',
  'The Good Place',
  'InuYasha',
  'Death Parade',
  'To Love-Ru',
  'The Last Ship',
  'Haikyu!!',
  '24',
  'DARLING in the FRANXX',
  'Sword Art Online Alternative: Gun Gale Online',
  'Toradora!',
  'Frasier',
  'Gold Rush',
  'Star Trek: The Next Generation',
  'Star Trek: Voyager',
  'Killing Eve',
  'Buffy the Vampire Slayer',
  'The Rookie',
  'Star Trek: Deep Space Nine',
  'A Million Little Things',
  'Preacher',
  'Is It Wrong to Try to Pick Up Girls in a Dungeon?',
  'Heartland',
  'Fate/stay night [Unlimited Blade Works]',
  'Aesthetica of a Rogue Hero',
  'Black Sails',
  "The Handmaid's Tale",
  'Sleepy Hollow',
  'Battlestar Galactica',
  'Ancient Aliens',
  'Divine Gate',
  'The Goldbergs',
  '12 Monkeys',
  'Billions',
  'Highschool of the Dead',
  "Dexter's Laboratory",
  'Stargate Atlantis',
  'Malcolm in the Middle',
  'The Curse of Oak Island',
  'White Collar',
  'Log Horizon',
  'Power',
  'WWE Raw',
  'Drake & Josh',
  'black-ish',
  'Designated Survivor',
  'Californication',
  'Puella Magi Madoka Magica',
  'Fresh Off the Boat',
  'MythBusters',
  'The Devil Is a Part-Timer!',
  'Murdoch Mysteries',
  'Steven Universe',
  'LEGO Ninjago: Masters of Spinjitzu',
  'Akame ga Kill!',
  'God Eater',
  'Rascal Does Not Dream of Bunny Girl Senpai',
  'Digimon Adventure',
  'Rizzoli & Isles',
  'Star Trek: Enterprise',
  'Monster Musume: Everyday Life with Monster Girls',
  'The Voice',
  'The Strain',
  'My Name Is Earl',
  'Ghost Whisperer',
  'Seraph of the End',
  "America's Funniest Home Videos",
  'Keeping Up with the Kardashians',
  'Broad City',
  'Married... with Children',
  'Star vs. the Forces of Evil',
  'Robot Chicken',
  "Marvel's Agent Carter",
  'Angel',
  'Storage Wars',
  'Fargo',
  'The Haves and the Have Nots',
  'King of the Hill',
  'Absolute Duo',
  'Medium',
  'Castle Rock',
  'Kill la Kill',
  'Ghost in the Shell: Stand Alone Complex',
  'Fate/Zero',
  'Cheers',
  'Black Butler',
  'Your Lie in April',
  'One Tree Hill',
  'Soul Eater',
  'A Certain Magical Index',
  'Baby Daddy',
  'Gurren Lagann',
  'Mystery Science Theater 3000',
  'The Shield',
  'Rugrats',
  'Rosewood',
  'Deadliest Catch',
  'The Librarians',
  'The Powerpuff Girls',
  'The Last Man on Earth',
  'Rosario + Vampire',
  'The Real Housewives of Atlanta',
  'Amagi Brilliant Park',
  'The Adventures of Jimmy Neutron: Boy Genius',
  'The Rifleman',
  'The Irregular at Magic High School',
  'Cowboy Bebop',
  'Nashville',
  "Haganai: I Don't Have Many Friends",
  "You're the Worst",
  'Psycho-Pass',
  'Arrested Development',
  'Revenge',
  'Curious George',
  'The Exorcist',
  "America's Got Talent",
  'Aria the Scarlet Ammo',
  'Awkward.',
  'Blood Blockade Battlefront',
  'Better Things',
  'The Amazing World of Gumball',
  'Parks and Recreation',
  'Caillou',
  'Numb3rs',
  'Shades of Blue',
  'Station 19',
  'Home Improvement',
  'Durarara!!',
  "Hell's Kitchen",
  'The Big Valley',
  'Saturday Night Live',
  'Silent Witness',
  'Remington Steele',
  'Ranma ½',
  'In Another World With My Smartphone',
  'M*A*S*H',
  'Everybody Hates Chris',
  'The View',
  'The Thundermans',
  'The Bridge',
  'Project Runway',
  '30 Rock',
  'Jeopardy!',
  'Hey Arnold!',
  'Ghost Adventures',
  'Magi',
  'Stargate Universe',
  'Merlin',
  'Forensic Files',
  'Pawn Stars',
  "Dawson's Creek",
  'The Mindy Project',
  'Regular Show',
  'The L Word',
  'Danganronpa: The Animation',
  'BTOOOM!',
  'Darker than Black',
  'Black Bullet',
  'Burn Notice',
  "America's Next Top Model",
  'grown-ish',
  'Monogatari',
  'The Incredible Hulk',
  'Teen Titans Go!',
  'Hollyoaks',
  'Guilty Crown',
  'Lie to Me',
  'Samurai Champloo',
  'Grimgar of Fantasy and Ash',
  'Animaniacs',
  'Speechless',
  'Garfield and Friends',
  'Angels of Death',
  'Sailor Moon',
  'The Golden Girls',
  'The Lord of the Skies',
  'The Boondocks',
  'Shark Tank',
  'The Beverly Hillbillies',
  'SIX',
  'The Amazing Race',
  'Life in Pieces',
  'We Bare Bears',
  "Marvel's Runaways",
  'The Pink Panther Show',
  'Lupin the Third',
  'Quantum Leap',
  'Firefly',
  'MasterChef',
  'Saving Hope',
  'The Affair',
  'Blood Lad',
  'The Addams Family',
  'The Familiar of Zero',
  'Superstore',
  'The Cleveland Show',
  'Big Time Rush',
  'Whose Line Is It Anyway?',
  'Atlanta',
  'Sekirei',
  'Alaskan Bush People',
  'American Housewife',
  'The Mick',
  '60 Days In',
  'The Bachelor',
  'Airwolf',
  'Simon & Simon',
  'Dollhouse',
  'Catfish: The TV Show',
  'Happy Days',
  'Yu-Gi-Oh! GX',
  'Family Matters',
  'Life',
  'Rescue Me',
  'Stigma of the Wind',
  'Shut Eye',
  'Shakugan no Shana',
  'The Outer Limits',
  'Miami Vice',
  'Wayward Pines',
  'Shameless',
  'Clannad',
  'Cardinal',
  'Bad Banks',
  'Boston Legal',
  'Harrow',
  'He-Man and the Masters of the Universe',
  'This Old House',
  'Witches of East End',
  'Scream Queens',
  "Marvel's Cloak & Dagger",
  'The O.C.',
  'The Real Housewives of Beverly Hills',
  'X-Men',
  'Misfits',
  'Spider-Man',
  'Metalocalypse',
  'H2O: Just Add Water',
  'Everwood',
  'Demon King Daimao',
  'The Penguins of Madagascar',
  'Peep Show',
  'The Killing',
  'Brickleberry',
  'Younger',
  'Yona of the Dawn',
  'My Teen Romantic Comedy SNAFU',
  'Prison School',
  'The Fruit of Grisaia',
  'For The People',
  'Dancing with the Stars',
  'NYPD Blue',
  'The Real Housewives of New Jersey',
  'Star',
  'The Cool Kids',
  'Splitting Up Together',
  'Another',
  'Devious Maids',
  'The First 48',
  'Taken',
  'Top of the Lake',
  'Chopped',
  'Taboo',
  'UnREAL',
  'Life Below Zero',
  'Dagashi Kashi',
  'Single Parents',
  'Himouto! Umaru-chan',
  'Dance Academy',
  '20/20',
  'Yu Yu Hakusho',
  'Good Trouble',
  'Vampire Knight',
  'Flashpoint',
  'Workaholics',
  'Sonic Boom',
  'Friday Night Lights',
  'Plastic Memories',
  '21 Jump Street',
  'Blackadder',
  '24: Legacy',
  'Dead Like Me',
  'The Practice',
  'Second Chance',
  'Burden of Truth',
  'Brothers and Sisters',
  'My 600-lb Life',
  'Ben 10',
  'Highlander: The Series',
  'Melrose Place',
  'Touch',
  'Sister Wives',
  'K.C. Undercover',
  'Faking It',
  'Popeye the Sailor',
  'The Brady Bunch',
  'LA to Vegas',
  'Yu-Gi-Oh! Zexal',
  '11.22.63',
  'All Saints',
  'Descendants of the Sun',
  'She-Ra: Princess of Power',
  'The Venture Bros.',
  'Doug',
  'The Asterisk War',
  'Salem',
  'Mary Kills People',
  'Drunk History',
  'Danny Phantom',
  'Face Off',
  'The Profit',
  'Wiseguy',
  'Mr. Bean',
  'Raising Hope',
  'Emerald City',
  'Street Outlaws',
  'Dimension W',
  'American Pickers',
  'Ironside',
  "Foster's Home for Imaginary Friends",
  'The Wonder Years',
  'Higurashi When They Cry',
  'Sonic X',
  'Forged in Fire',
  'The Catch',
  'The Brave',
  'Mobile Suit Gundam SEED',
  'Hellsing Ultimate',
  'Top Chef',
  'Dinosaurs',
  'Finding Carter',
  'Boy Meets World',
  'Sailor Moon Crystal',
  'Bring It!',
  'Fixer Upper',
  'The Twilight Zone',
  'Alfred Hitchcock Presents',
  'Made in Chelsea',
  "Fast N' Loud",
  'Accel World',
  'Meet the Press',
  'Doc McStuffins',
  'Crayon Shin-chan',
  '.hack',
  'ER',
  'The Office',
  'Classroom of the Elite',
  'Renegade',
  "Dirk Gently's Holistic Detective Agency",
  'So You Think You Can Dance',
  'Greek',
  'Dance Moms',
  'Sanford and Son',
  'The Saint',
  'Offspring',
  'Full Metal Panic!',
  'Kamisama Kiss',
  'River Monsters',
  'The Path',
  'The Qwaser of Stigmata',
  'Little Britain',
  'Beyond the Boundary',
  'Step by Step',
  'The Ultimate Fighter',
  'Lodge 49',
  'Snow White with the Red Hair',
  'Inside No. 9',
  'Primeval',
  'TRIGUN',
  'Roswell',
  'Bordertown',
  'The Outer Limits',
  'Ghosted',
  "Yu-Gi-Oh! 5D's",
  'Legend of the Seeker',
  'Inspector Gadget',
  'Proven Innocent',
  'Parenthood',
  'Vanderpump Rules',
  'Lost in Space',
  'Letterkenny',
  'Spiral',
  'Perception',
  'Over the Garden Wall',
  'A.P. Bio',
  'Queen Sugar',
  'PEN15',
  'K-Project',
  'Breakout Kings',
  'Afro Samurai',
  'Long Island Medium',
  'I Love Lucy',
  'Taxi',
  'Cougar Town',
  'Battlestar Galactica',
  'The Musketeers',
  'Southland',
  'Harlots',
  'The Heroic Legend of Arslan',
  'The Bernie Mac Show',
  'General Hospital',
  'Daria',
  'Rise',
  'Schooled',
  'The Pet Girl of Sakurasou',
  'Naked and Afraid',
  'Mistresses',
  'Flying Witch',
  'Line of Duty',
  'Black Books',
  'Angie Tribeca',
  'Boruto: Naruto Next Generations',
  'Oreimo',
  'Leah Remini: Scientology and the Aftermath',
  'Tyrant',
  'Tokyo Ravens',
  'Tokyo Ravens',
  'Doc Martin',
  'The Dick Van Dyke Show',
  'Amagami SS',
  'Persona 5 the Animation',
  'Wilfred',
  'The Commish',
  'The Conners',
  'Homicide Hunter: Lt Joe Kenda',
  'Moonlight Drawn by Clouds',
  'Chowder',
  'Melissa & Joey',
  'Hard Sun',
  'Wings',
  'Marriage Boot Camp: Reality Stars',
  'Blade Dance of Elementalers',
  'Key & Peele',
  'I Am Jazz',
  'Maid Sama!',
  'St. Elsewhere',
  'Outsiders',
  'Sliders',
  'The Bachelorette',
  'Total Divas',
  "Gordon Ramsay's 24 Hours to Hell and Back",
  'The Real Housewives of Orange County',
  'The Unit',
  'Louie',
  'The League',
  'K-ON!',
  'Make It or Break It',
  'Spooks',
  'Hunter',
  'Swamp People',
  'Beat Bobby Flay',
  'Ask This Old House',
  'Bungo Stray Dogs',
  'The Masked Singer',
  '90 Day Fiancé',
  'Living Single',
  'Good Luck Charlie',
  'Cake Boss',
  'Yu-Gi-Oh! Arc-V',
  'World Break: Aria of Curse for a Holy Swordsman',
  'The Secret Life of the American Teenager',
  'Black Lagoon',
  'Devils Line',
  'Man vs. Wild',
  'WWE SmackDown Live',
  'The Bold Type',
  'House Hunters International',
  'Four Weddings',
  'Reba',
  'Graceland',
  'United States of Tara',
  'Ouran High School Host Club',
  'Trial & Error',
  'Body of Proof',
  'The Glades',
  'Fear Factor',
  'Devil May Cry',
  'Is This a Zombie?',
  'Unsolved Mysteries',
  'Outbreak Company',
  'Kevin (Probably) Saves the World',
  'My Life as a Teenage Robot',
  'Mushi-Shi',
  'Mushi-Shi',
  'Newhart',
  'Terror in Resonance',
  'Air Gear',
  'Private Practice',
  'StarTalk with Neil deGrasse Tyson',
  'Aldnoah.Zero',
  'Majikoi - Oh! Samurai Girls',
  'The Fall Guy',
  'The Only Way Is Essex',
  "Agatha Christie's Marple",
  'Coupling',
  'Pride and Prejudice',
  'The Looming Tower',
  'Teenage Mutant Ninja Turtles',
  'Married at First Sight',
  'Claymore',
  'Damien',
  "Guy's Grocery Games",
  'Diabolik Lovers',
  'Undefeated Bahamut Chronicle',
  'Our Cartoon President',
  'I Spy',
  'Laverne & Shirley',
  'The Four: Battle for Stardom',
  'Jeremiah',
  'Good Behavior',
  'Miles from Tomorrowland',
  'The Pioneer Woman',
  'Perfect Strangers',
  'WWE NXT',
  'The Detour',
  'Duck Dynasty',
  'Handy Manny',
  'Austin & Ally',
  'Alvinnn!!! and The Chipmunks',
  'Dog With a Blog',
  'Every Witch Way',
  'Absolutely Fabulous',
  'ERASED',
  '10 Things I Hate About You',
  'A.N.T. Farm',
  'War and Peace',
  'The Bob Newhart Show',
  'Lonesome Dove',
  'Alone Together',
  'Taggart',
  'American Ninja Warrior',
  'The Thick of It',
  'Clannad After Story',
  'Little Women: LA',
  'Wolfblood',
  'Take Two',
  'Penn & Teller: Bullshit!',
  'The Son',
  'MEGALOBOX',
  'Flip or Flop',
  'Infinite Stratos',
  'Baskets',
  'Maken-ki!',
  'Baka and Test: Summon the Beasts',
  'Expedition Unknown',
  'Claws',
  'Angry Birds Toons',
  'Happy Endings',
  'Hill Street Blues',
  'Golden Time',
  'Say Yes to the Dress',
  'Shark',
  'Hoarders',
  'School of Rock',
  'Bizarre Foods: Delicious Destinations',
  'Clarence',
  'From Me to You',
  'Spaced',
  "Don't Trust the B---- in Apartment 23",
  'A Certain Scientific Railgun',
  'Fraggle Rock',
  "Here's Lucy",
  'Campione!',
  'Legends',
  'Tenchi Muyo! War on Geminar',
  'Sanjay and Craig',
  'The Dead Files',
  'Intervention',
  'The Bastard Executioner',
  'Light as a Feather',
  'Love Island',
  'Dies Irae',
  'Cross Ange: Rondo of Angels and Dragons',
  'Dragonar Academy',
  'The Event',
  'The Next Step',
  'The Real Housewives of New York City',
  "I'm Dying Up Here",
  'Total Bellas',
  'Ugly Betty',
  'SpongeBob SquarePants',
  'The First',
  'Good Times',
  'Braquo',
  'Celebrity Undercover Boss',
  'X-Men: Evolution',
  'Deutschland',
  'Spice and Wolf',
  'Invader Zim',
  'Rurouni Kenshin',
  'Chance',
  'Naked and Afraid XL',
  'Kung Fu Panda: Legends of Awesomeness',
  'W: Two Worlds',
  'Worst Cooks in America',
  'The Legend of the Blue Sea',
  "History's Strongest Disciple Kenichi",
  'FLCL',
  'Property Brothers',
  'Gangland Undercover',
  'The Game',
  'WATAMOTE',
  "Chio's School Road",
  'The Mighty Boosh',
  "Tyler Perry's If Loving You Is Wrong",
  'GATE',
  'Mr. D',
  'DCI Banks',
  'Oreshura',
  'The White Shadow',
  'Blue Dragon',
  'My Super Sweet 16',
  "McLeod's Daughters",
  'Digimon Tamers',
  'Weird Science',
  'Akane-iro ni Somaru Saka',
  'The Mary Tyler Moore Show',
  'American Greed',
  'House Hunters',
  'Detectorists',
  'Land of the Giants',
  'Aoharu x Machinegun',
  'Atlantis',
  'The Guardian',
  'Better Off Ted',
  'Silk Stalkings',
  'Project Runway All Stars',
  'Ally McBeal',
  'Sleeper Cell',
  'The Rockford Files',
  'The Incredible Dr. Pol',
  'Rel',
  'The Kids Are Alright',
  'Justice League Action',
  'The Real Housewives of Potomac',
  'Feed the Beast',
  'Mr. Pickles',
  'Time After Time',
  'Roots',
  'Uncle Grandpa',
  'Ben 10: Omniverse',
  'Black Blood Brothers',
  'The Marvelous Misadventures of Flapjack',
  'Guidance',
  'Sirens',
  'D.Gray-man',
  'Mister Ed',
  'Graves',
  'Dietland',
  'I Feel Bad',
  'The Little Couple',
  'Lou Grant',
  'Home Movies',
  'Freakish',
  'Champions',
  'Man Seeking Woman',
  'Bachelor in Paradise',
  'Being Erica',
  'Underground',
  'Ushio to Tora',
  'Rhoda',
  'Steins;Gate 0',
  'ClassicaLoid',
  'The Alec Baldwin Show',
  'Saving Grace',
  'Top Gear',
  'Wolf Girl & Black Prince',
  'WWE Superstars',
  'Jimmy Kimmel Live!',
  'Robin Hood',
  'The Lucy Show',
  'Saved by the Bell',
  'Ergo Proxy',
  'Chaika - The Coffin Princess',
  "Haven't You Heard? I'm Sakamoto",
  'Mysteries at the Museum',
  'Burning Love',
  'The Bridge',
  'The Triangle',
  'Party Down',
  'Tiny Toon Adventures',
  'Plebs',
  'Toriko',
  'Blue Spring Ride',
  'Martian Successor Nadesico',
  'Magical Warfare',
  'Flipping Out',
  'Jormungand',
  'Mobile Suit Gundam: Iron-Blooded Orphans',
  'X Company',
  'Sealab 2021',
  'The Paynes',
  'Tanked',
  'Food Network Star',
  'All Night',
  'Making It',
  'Rage of Bahamut',
  'Lord Marksman and Vanadis',
  'The Bisexual',
  'Boys Over Flowers',
  'Man v. Food',
  'John Doe',
  'Cold Case Files',
  'Rake',
  'Chrome Shelled Regios',
  'In the Flesh',
  'The PJs',
  'Manhattan',
  'Real Humans',
  'Bering Sea Gold',
  'The Odd Couple',
  'Selfie',
  'Blast of Tempest',
  'Pinky and the Brain',
  'Monster Rancher',
  'Dirty Sexy Money',
  'Clique',
  'Scott & Bailey',
  'Cardfight!! Vanguard',
  'Prime Suspect',
  'Dice',
  'Your Pretty Face Is Going to Hell',
  'Kitchen Nightmares',
  'Alone',
  'Gangsta.',
  'The Greatest American Hero',
  "Chaos Dragon: Sekiryuu Sen'eki",
  'Stan Against Evil',
  'Obsession: Dark Desires',
  'Please Like Me',
  'Yu-Gi-Oh!',
  'Twisted',
  'Marlon',
  'Great British Menu',
  'My Big Fat Fabulous Life',
  'T@gged',
  'Deadbeat',
  'L.A. Hair',
  'Find Me in Paris',
  'Jane Eyre',
  '7th Heaven',
  'Agent X',
  'Terra Formars',
  'Code:Breaker',
  'Bakuman',
  'My Dead Ex',
  'Land of Honor',
  'Black Cat',
  'Cutthroat Kitchen',
  'Bella and the Bulldogs',
  'The Eric Andre Show',
  'MasterChef Junior',
  'Shots Fired',
  'Son of Zorn',
  'Maoyū Maō Yūsha',
  'Running Wild with Bear Grylls',
  'Difficult People',
  'Bizarre Foods with Andrew Zimmern',
  'The Biggest Loser',
  'Webster',
  'Gavin & Stacey',
  'The Invisible Man',
  ' Girls und Panzer',
  'Kiri',
  "Hangin' with Mr. Cooper",
  'Eli Stone',
  'Brotherhood',
  'Lost in Austen',
  'Pocoyo',
  'Sky Wizards Academy',
  'NTSF:SD:SUV::',
  'Inside the NFL',
  'Junjo Romantica',
  'Horace and Pete',
  'Resurrection',
  'The Split',
  'Zetman',
  'xxxHOLiC',
  'Jumanji',
  'Late Night with Seth Meyers',
  'Felicity',
  'Guyver: The Bioboosted Armor',
  'Place to Place',
  'Friday Night Dinner',
  'Aquarion',
  'The Circus',
  'Dance with Devils',
  'Love Thy Neighbor',
  'Anthony Bourdain: No Reservations',
  'Father Knows Best',
  "McHale's Navy",
  'Voyage to the Bottom of the Sea',
  'Close Up with The Hollywood Reporter',
  'Basilisk',
  'Whitechapel',
  'The Voice',
  'Kids Baking Championship',
  'Inside Amy Schumer',
  'Braxton Family Values',
  'Hunting Hitler',
  'Diesel Brothers',
  'The Code',
  'Speed Racer',
  'Restaurant: Impossible',
  'Ellen',
  'False Flag',
  'Camelot',
  'Broken Blade',
  'Adam-12',
  'Robin of Sherwood',
  'Gungrave',
  'Kojak',
  'A Crime to Remember',
  'Dimension 404',
  'Madeline',
  'Primeval: New World',
  'Eden of the East',
  'Beck',
  'A Bit of Fry and Laurie',
  'Voltron: Defender of the Universe',
  'Record of Grancrest War',
  'The Long Road Home',
  'Blood-C',
  'TRON: Uprising',
  'Barbarians Rising',
  'Moral Orel',
  'Norn9: Norn+Nonet ',
  'Bleak House',
  'World Trigger',
  'Atelier Escha & Logy : Alchemists of the Dusk Sky',
  'The Chi',
  'Kendra on Top',
  'Oh My Venus',
  'Garo: The Animation',
  'Cold Squad',
  'The Riches',
  'The Sacred Blacksmith',
  'Fresh Meat',
  'Major Dad',
  'American Gothic',
  'My So-Called Life',
  'Midnattssol',
  'Rabbids Invasion',
  'Rin-ne',
  'The Powerpuff Girls',
  'Return to Lonesome Dove',
  'Republic of Doyle',
  "Britain's Best Home Cook",
  'Outnumbered',
  'The Hunt with John Walsh',
  'World of Dance',
  'Gargantia on the Verdurous Planet',
  'Wicked Tuna: Outer Banks',
  'Acapulco H.E.A.T.',
  'Heartstrings',
  'Unikitty',
  "Monthly Girls' Nozaki-kun",
  'The Carmichael Show',
  'Dual Survival',
  'Samurai Harem',
  'While You Were Sleeping',
  'Negima! Magister Negi Magi',
  'Maya & Miguel',
  'Little Big Shots',
  'Little Women: Atlanta',
  "Cooper Barrett's Guide to Surviving Life",
  'Inu x Boku Secret Service',
  'Lip Service',
  'Sid the Science Kid',
  'Law & Order True Crime',
  'Hunter Street',
  'Sense and Sensibility',
  'Intruders',
  'Comet Lucifer',
  'Blade and Soul',
  "Kino's Journey",
  'Beautiful Bones: Sakurako’s Investigation',
  'Mashiroiro Symphony: The Color of Lovers',
  'Miranda',
  'Classroom Crisis',
  'Last Exile',
  'Day Break',
  'To Tell the Truth',
  'D.Gray-man Hallow',
  'That Girl',
  'Legit',
  'Alaska: The Last Frontier',
  'Toddlers & Tiaras',
  "Movin' On",
  'Sex&amp;Drugs&amp;Rock&amp;Roll',
  "Ellen's Game of Games",
  'Cheese in the Trap',
  'Buddy Complex',
  'Axe Cop',
  'Welcome to Sweden',
  'Deadly Women',
  '205 Live',
  'Oliver Twist',
  'Making History',
  'Frisky Dingo',
  'Fate/stay night',
  'Getting On',
  'Kämpfer',
  'Fruits Basket',
  'Filthy Rich',
  'The Wubbulous World of Dr. Seuss',
  'Attack on Titan: Junior High',
  'Hakumei and Mikochi',
  'The League of Gentlemen',
  'Soul Eater Not!',
  'Upper Middle Bogan',
  'Little Women: Dallas',
  'Say I love you.',
  'Persona 4 The Animation',
  'Samurai 7',
  "Rick Steves' Europe",
  'My Mad Fat Diary',
  'Disappeared',
  'Emma',
  'Love Stage!!',
  'Puppy Bowl',
  'Yukon Men',
  'Blossom',
  'Party Legends',
  'Punch Line',
  'Max Steel',
  'Look Around You',
  'The Shadow Line',
  'Kids on the Slope',
  'Skin Wars',
  'Samantha Who?',
  'Bunheads',
  'Kingpin',
  'Nisekoi',
  'Corpse Princess',
  'My Love Story!!',
  'Highlander: The Raven',
  "F*ck That's Delicious",
  'Weediquette',
  'School Rumble',
  'Beyond Scared Straight',
  'Alias Smith and Jones',
  'Born This Way',
  'Upstairs Downstairs',
  'Dragonaut: The Resonance',
  'Three Sheets',
  'Rebus',
  'Gun Sword',
  'Worth It',
  'The Prince of Tennis',
  'The Wrong Mans',
  'Valvrave the Liberator',
  'Getting On',
  'Outsourced',
  'Bunnytown',
  'Forged in Fire: Knife or Death',
  'Brockmire',
  'Extreme Ghostbusters',
  'My Favorite Martian',
  'No Activity',
  'Cyberwar',
  'The Kennedys',
  'Dragon Ball GT',
  'Nightcap',
  'Trust Me',
  'Iron Man: Armored Adventures',
  'T.U.F.F. Puppy',
  'The Fades',
  'I Am Cait',
  'Mobile Suit Gundam 00',
  'East Los High',
  '90 Day Fiancé: Before the 90 Days',
  'Gunslinger Stratos: The Animation',
  'Zac & Mia',
  'The Enfield Haunting',
  'Banana',
  'Nightline',
  'Unusual Suspects',
  "Australia's Next Top Model",
  'What on Earth?',
  'Young Hercules',
  'Pandora Hearts',
  'Mekakucity Actors',
  'Billy on the Street',
  'Shiki',
  'The Story of Film: An Odyssey',
  'The Tesla Files',
  'The Trade',
  'The Titan Games',
  'Arms Alchemy',
  'Holiday Baking Championship',
  'Kevin from Work',
  'L.A. Dragnet',
  'Black Jesus',
  'Saved by the Bell: The College Years',
  'Game Face',
  'The Aliens',
  "Tim and Eric's Bedtime Stories",
  'Saiyuki Reload Blast',
  'Hayate the Combat Butler',
  'Survivorman',
  'Brave 10',
  'OutDaughtered',
  'Ax Men',
  'Nathan For You',
  'This Is Life with Lisa Ling',
  'Pure',
  "Hikaru's Go",
  'Married',
  'Astro Boy',
  'Slayers',
  'Horrible Histories',
  'Scorned: Love Kills',
  'Who Do You Think You Are?',
  'Space Dandy',
  'Hiiro no Kakera - The Tamayori Princess Saga',
  'Itazura na Kiss',
  'Love It or List It',
  'Phantasy Star Online 2: The Animation',
  'Matador',
  'Max Steel',
  'Nightwatch',
  'The Last Alaskans',
  'The Munsters Today',
  'The Cartel',
  'Silk',
  'Behind Bars: Rookie Year',
  'Detroit 1-8-7',
  'The Joy of Painting',
  'Uta no Prince-sama',
  'Below the Surface',
  'Packed to the Rafters',
  'Daniel Deronda',
  'Wicked Tuna',
  'Bridezillas',
  'The Tower of Druaga: The Aegis of Uruk',
  'Gugure! Kokkuri-san',
  'Stella',
  'Moone Boy',
  'Black Market: Dispatches',
  'The Three Stooges',
  'Roseanne',
  'Spy',
  'Heavy Object',
  'Million Dollar Matchmaker',
  'Mobile Suit Gundam Wing',
  'Space Brothers',
  'Planet Sheen',
  'Hunderby',
  'Veni Vidi Vici',
  'Beat Shazam',
  'Zero Hour',
  'Kitchen Confidential',
  'Criminal Justice',
  'The Firm',
  'Vanished',
  'Tokyo ESP',
  "There's... Johnny!",
  "Dante's Cove",
  'THE REFLECTION',
  'Escaping Polygamy',
  'Man Up!',
  'The Loop',
  'Gap Year',
  'Little Mosque on the Prairie',
  'Coppelion',
  'Tokyo Magnitude 8.0',
  'Astro Boy',
  'Travel Man: 48 Hours in...',
  'Boogiepop Phantom',
  'The F Word',
  'Kingdom',
  'Last Call with Carson Daly',
  'Abandoned',
  'Lucky Romance',
  'Jane by Design',
  'The Great Food Truck Race',
  'The Comedians',
  'Better Late Than Never',
  'Flea Market Flip',
  'LEGO Friends',
  'Chopped Junior',
  'Utopia',
  'Mama June: From Not to Hot',
  'The Romeo Section',
  'Iron Chef America',
  'Tree Fu Tom',
  'Nightmare Next Door',
  'United Shades of America',
  'Spring Baking Championship',
  'Witchblade',
  'Mighty Magiswords',
  'The Millionaire Matchmaker',
  'The Kennedys',
  'Treasure Quest: Snake Island',
  'Make It Pop',
  'Bong Appétit',
  'National Treasure',
  'Nanny and the Professor',
  'The New Woody Woodpecker Show',
  'Mary Mary',
  "The Hitchhiker's Guide to the Galaxy",
  'Hakkenden: Eight Dogs of the East',
  'The Secret of Crickley Hall',
  'BuzzFeed Unsolved - True Crime',
  'Cucumber',
  'Big Windup!',
  'The Nine Lives of Chloe King',
  'The Hunt for the Zodiac Killer',
  'Jo',
  'Hakuoki -Demon Of The Fleeting Blossom-',
  'Fox News Sunday',
  'WWE Main Event',
  '90 Day Fiancé: Happily Ever After?',
  'The Danny Thomas Show',
  'Conviction',
  'Mischief of the Gods',
  'Heroic Age',
  'Injustice',
  'Doomsday Preppers',
  'NARUTO Spin-Off: Rock Lee & His Ninja Pals',
  'Celebrity Family Feud',
  "Oda Nobuna's Ambition",
  'Banished',
  'Hollywood Game Night',
  'Atelier',
  'Prey',
  'Broken Angel',
  'Him & Her',
  "OK K.O.! Let's Be Heroes",
  'Please Twins!',
  'Streets of Laredo',
  'Fated to Love You',
  'Napoleon Dynamite',
  'The Chew',
  'Eagleheart',
  'Girls Beyond the Wasteland',
  'The Last Panthers',
  'Sherlock Holmes',
  'Dog Whisperer',
  'Lark Rise to Candleford',
  'Top Chef Masters',
  'The Slap',
  'Utawarerumono: The False Faces',
  'Kourtney and Khloé Take Miami',
  'Tiger & Bunny',
  'The Book of Negroes',
  'Home Free',
  'The History of Comedy',
  'Delocated',
  'Lincoln Heights',
  'Standoff',
  "Hamilton's Pharmacopeia",
  'Threesome',
  "Victoria's Secret Fashion Show",
  'Project Runway Junior',
  'Hate Thy Neighbor',
  'Drifters',
  'Fugget About It',
  'Archangel',
  'Part of Me',
  'Bedlam',
  'Nabari no Ou',
  "Chloe's Closet",
  'Bluestone 42',
  'The Other Guy',
  'Maison Close',
  'David Copperfield',
  'The Beautiful Lie',
  'Primal Survivor',
  'Paradox',
  'An American Murder Mystery: The Staircase',
  'Bleak House',
  'Ninja Nonsense',
  'The Adventures of Paddington Bear',
  'The Principal',
  'American Gladiators',
  'This Country',
  'Kaleido Star',
  'The F Word',
  'Brothers Conflict',
  'Psychic Detective Yakumo',
  'The Dick Cavett Show',
  'Hangar 1: The UFO Files',
  'Outlaw Star',
  'Daisy of Love',
  'Hopalong Cassidy',
  'Pasión Prohibida',
  'Dead Boss',
  'Good Doctor',
  'Wives with Knives',
  'Buzzfeed Unsolved - Supernatural',
  'Hetalia',
  'The Killer Speaks',
  'The Murder of Laci Peterson',
  'Ultraviolet',
  'Cash Cab',
  'Stacked',
  'Tenchi Muyô! GXP',
  'Life of Kylie',
  'Battleground',
  'Uncle',
  'The Passing Bells',
  'Pramface',
  'The Gong Show',
  'The Hotwives of Orlando',
  'The Toy Box',
  "Fluffy's Food Adventures",
  'Princess Tutu',
  'Please Teacher!',
  'Who The (Bleep) Did I Marry?',
  'Vandread',
  'Living With Fran',
  'Match Game',
  'Cockroaches',
  'The Great American Baking Show',
  'Love Connection',
  'Kourtney and Kim Take New York',
  'Cupcake Wars',
  'Wasted',
  'American Ripper',
  "America's Book of Secrets",
  'The High Fructose Adventures of Annoying Orange',
  'Boy Band',
  'What Would Diplo Do?',
  'Caribbean Life',
  'Prince of Stride: Alternative',
  'Gigantor',
  'Psychic Investigators',
  'Good Bones',
  'Brother vs. Brother',
  'Watch Over Me',
  'Jodi Arias: An American Murder Mystery',
  'My Big Fat Pet Makeover',
  'Peacemakers',
  'What Would You Do?',
  'Just Between Lovers',
  'Party Girl',
  'Total Wipeout',
  'Tayo the Little Bus',
  'Return to the Planet of the Apes',
  'Dragnet',
  'Prisoners of War',
  'Iron Chef Gauntlet',
  'The Strange Calls',
  'Zatch Bell!',
  'The FBI Files',
  'Gensomaden Saiyuki',
  'Quick Draw',
  'The Awesomes',
  'Siblings',
  'Tamar & Vince',
  'Major Lazer',
  "Finding Escobar's Millions",
  'Steven Seagal: Lawman',
  'The Wall',
  'Future Card Buddyfight',
  'Insane Pools: Off the Deep End',
  'Chickens',
  'Pororo the Little Penguin',
  'Dream Corp LLC',
  'One Week Friends',
  'You Bet Your Life',
  'Dates',
  'Anyone But Me',
  'Muv-Luv Alternative: Total Eclipse',
  'A Day in the Life',
  'Who Killed Tupac?',
  'Celebrity Ghost Stories',
  'Wild Things with Dominic Monaghan',
  'The Proposal',
  'Ranger Rob',
  'Are You Smarter Than a 5th Grader?',
  'American Gladiators',
  'Good Morning America',
  "Hello Kitty's Furry Tale Theater",
  "James May's Man Lab",
  'Zorro the Chronicles',
  'Stephen Fry in America',
  'Desert Punk',
  'Dreamland',
  'Safe Harbor',
];

module.exports = hulu;
